name: Node.js

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build:
        runs-on: ubuntu-latest

        node-version: [16.x]

        env:
            JWT_SECRET: ${{secrets.JWT_SECRET}}
            NODE_ENV: ${{secrets.JWT_SECRET}}
            PORT: ${{secrets.JWT_SECRET}}
            EMAIL_HOST: ${{secrets.JWT_SECRET}}
            EMAIL_USERNAME: ${{secrets.JWT_SECRET}}
            EMAIL_PASSWORD: ${{secrets.JWT_SECRET}}
            FROM_EMAIL: ${{secrets.JWT_SECRET}}

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 16.x
            - name: Install node packages
                run: npm install
            - name: Install dependencies
                run: npm test
