name: Node.js

on:
    push:
        branches: [main, master, event_refactor]
    pull_request:
        branches: [main, master, event_refactor]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            JWT_SECRET: ${{secrets.JWT_SECRET}}
            NODE_ENV: ${{secrets.JWT_SECRET}}
            PORT: ${{secrets.JWT_SECRET}}
            EMAIL_HOST: ${{secrets.JWT_SECRET}}
            EMAIL_USERNAME: ${{secrets.JWT_SECRET}}
            EMAIL_PASSWORD: ${{secrets.JWT_SECRET}}
            FROM_EMAIL: ${{secrets.JWT_SECRET}}
        strategy:
            matrix:
                node-version: [15.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install node packages
                run: npm install
            - name: Install dependencies
                run: npm test
