name: Node.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
              env:
                  CI: true
                  JWT_SECRET: ${{secrets.JWT_SECRET}}
                  NODE_ENV: ${{secrets.JWT_SECRET}}
                  PORT: ${{secrets.JWT_SECRET}}
                  EMAIL_HOST: ${{secrets.JWT_SECRET}}
                  EMAIL_USERNAME: ${{secrets.JWT_SECRET}}
                  EMAIL_PASSWORD: ${{secrets.JWT_SECRET}}
                  FROM_EMAIL: ${{secrets.JWT_SECRET}}
